dist: xenial
sudo: required
services:
  - docker
script:
  - docker pull tyrrrz/discordchatexporter
  - bash updateArchive.sh
  - bash gitPushUpdatedRepo.sh
  - docker build -t komodo_discord_archive_docs_image .
  - docker run --rm -v $(pwd):/app/ -w /app/ -u $(id -u):$(id -g) komodo_discord_archive_docs_image
  - cd docs/.vuepress/dist/
  - echo 'discord.komodo.lordofthechains.com' > CNAME

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    local-dir: docs/.vuepress/dist/
    repo: gcharang/discord-archive-komodo
    on:
      branch: master

branches:
  only:
    - master
