app:
  build: .
  ports:
    - 8080:8080
  volumes:
    - .:/app/
  container_name: komodo_discord_archive_docs_image
  user: "1000:1000"
  command:
    - yarn install && yarn docs:build && tail -f /dev/null/
  stdin_open: true
